spring:
  application:
    name: scta-service-call-feign-consumer-okhttp
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  httpclient:
    # 是否开启。默认为 true
    enabled: false
  okhttp:
    # 是否开启。默认为 false
    enabled: true

server:
  port: 28080