spring:
  application:
    name: scta-mq-stream-kafka-producer-actuator
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binder 配置项，对应 BinderProperties Map
      # binders:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        # 目的地。这里使用 Kafka Topic
        demo01-output:
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
      # Spring Cloud Stream Kafka 配置项
      kafka:
        # Kafka Binder 配置项，对应 KafkaBinderConfigurationProperties 类
        binder:
          # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
          brokers: 127.0.0.1:9092
        # Kafka 自定义 Binding 配置项，对应 KafkaBindingProperties Map
        bindings:
          demo01-output:
            # Kafka Producer 配置项，对应 KafkaProducerProperties 类
            producer:
              # 是否同步发送消息，默认为 false 异步。
              sync: true
management:
  endpoints:
    web:
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        include: '*'
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      # 是否开启。默认为 true 开启。
      enabled: true
      # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
      show-details: ALWAYS

server:
  port: 18080