spring:
  application:
    name: scta-register-center-zookeeper-consumer
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      # Zookeeper 作为注册中心的配置项，对应 ZookeeperDiscoveryProperties 配置类
      discovery:
        # Zookeeper 数据存储的根节点，默认为 /services
        root: /services

server:
  port: 28080