spring:
  application:
    name: scta-mq-stream-rabbitmq-producer-confirm
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binder 配置项，对应 BinderProperties Map
      binders:
        rabbit001:
          # 设置 Binder 的类型
          type: rabbit
          # 设置 Binder 的环境配置
          environment:
            # 如果是 RabbitMQ 类型的时候，则对应的是 RabbitProperties 类
            spring:
              rabbitmq:
                # RabbitMQ 服务的地址
                host: 127.0.0.1
                # RabbitMQ 服务的端口
                port: 5672
                # RabbitMQ 服务的账号
                username: guest
                # RabbitMQ 服务的密码
                password: guest
                # 设置消息是否回退，默认为 false
                publisher-returns: true
                # 设置开启消息确认模型，默认为 null 不进行确认
                publisher-confirm-type: simple
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        demo01-output:
          # 目的地。这里使用 RabbitMQ Exchange
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
          # 设置使用的 Binder 名字
          binder: rabbit001
          producer:
            # 是否开启异常 Channel，默认为 false 关闭
            error-channel-enabled: true
      # RabbitMQ 自定义 Binding 配置项，对应 RabbitBindingProperties Map
      rabbit:
        bindings:
          demo01-output:
            # RabbitMQ Producer 配置项，对应 RabbitProducerProperties 类
            producer:
              # 设置发送确认的 Channel，默认为 null
              confirm-ack-channel: demo01-producer-confirm


  server:
    port: 18080