spring:
  application:
    name: scta-service-tolerance-sentinel-file-provider
  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      # 是否开启。默认为 true 开启
      enabled: true
      # 是否饥饿加载。默认为 false 关闭
      eager: true
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:7070
      filter:
        # 拦截请求的地址。默认为 /*
        url-patterns: /**
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          file:
            # 配置规则所在文件。
            file: /Users/Dumas/Sentinel/demo-provider/flow-rule.json
            # 定时读取实现刷新，默认为 3000 毫秒。
            recommendRefreshMs: 3000
            # 数据格式
            data-type: json
            # 规则类型
            rule-type: FLOW
