spring:
  application:
    name: scta-register-center-eureka-client
server:
  port: 28080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      # defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/  安全认证模式
