spring:
  application:
    name: zookeeper-provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      # ZooKeeper 作为注册中心的配置项，对应 ZooKeeperDiscoveryProperties 配置类
      discovery:
        # ZooKeeper 数据存储的根节点，默认为 /services
        root: /services

server:
  port: 18080