spring:
  application:
    name: scta-service-call-feign-consumer-external
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 28080