server:
  # 服务器端口，设置为 18080 避免和本地的 Apollo 端口冲突
  port: 18080

# Apollo 相关配置项
app:
  # 使用的 Apollo 的项目（应用）编号
  id: ${spring.application.name}
apollo:
  # Apollo Meta Server 地址
  meta: http://127.0.0.1:8080
  bootstrap:
    # 是否开启 Apollo 配置预加载功能。默认为 false。
    enabled: true
    eagerLoad:
      # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
      enable: true
      # 使用的 Apollo 的命名空间，默认为 application
    namespaces: application

spring:
  application:
    name: scta-service-tolerance-sentinel-apollo-provider
  cloud:
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      # 是否开启。默认为 true 开启
      enabled: true
      # 是否饥饿加载。默认为 false 关闭
      eager: true
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:7070
      filter:
        # 拦截请求的地址。默认为 /*
        url-patterns: /**
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          apollo:
            # Apollo 命名空间
            namespaceName: application
            # Apollo 配置 key
            flowRulesKey: sentinel.flow-rule
            # 数据格式
            data-type: json
            # 规则类型
            rule-type: FLOW
