spring:
  application:
    name: scta-service-call-ribbon-consumer-eager
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 28080

ribbon:
  # Ribbon 饥饿加载配置项，对应 RibbonEagerLoadProperties 配置类
  eager-load:
    # 是否开启饥饿加载。默认为 false 不开启
    enabled: true
    # 开启饥饿加载的 Ribbon 客户端名字。如果有多个，使用 , 逗号分隔。
    clients: scta-service-call-ribbon-provider
