spring:
  application:
    name: scta-service-call-ribbon-consumer-retry
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 28080

ribbon:
  restclient:
    # 设置使用 Jersey Client，对应 RestClientRibbonConfiguration 配置类
    enabled: true

demo-provider:
  ribbon:
    # 请求的连接超时时间，单位：毫秒。默认为 1000
    ConnectTimeout: 1000
    # 请求的读取超时时间，单位：毫秒。默认为 1000
    ReadTimeout: 1
    # 是否对所有操作都进行重试，默认为 false。
    OkToRetryOnAllOperations: true
    # 对当前服务的重试次数，默认为 0 次。
    MaxAutoRetries: 0
    # 重新选择服务实例的次数，默认为 1 次。注意，不包含第 1 次哈。
    MaxAutoRetriesNextServer: 1
