spring:
  application:
    name: scta-mq-stream-rocketmq-provider-aliyun
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        demo01-output:
          # 目的地。这里使用 RocketMQ Topic
          destination: TOPIC_YUNAI_TEST
          # 内容格式。这里使用 JSON
          content-type: application/json
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          # RocketMQ Namesrv 地址
          name-server: onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
          # 阿里云账号 AccessKey
          access-key: ${ALIYUN_ACCESS_KEY}
          # 阿里云账号 SecretKey
          secret-key: ${ALIYUN_SECRET_KEY}
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          demo01-output:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              # 生产者分组
              group: GID_PRODUCER_GROUP_YUNAI_TEST
              # 是否同步发送消息，默认为 false 异步。
              sync: true

server:
  port: 18080