spring:
  application:
    name: scta-service-call-ribbon-consumer-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 28080

#ribbon:
#  okhttp:
#    enabled: true # 设置使用 OkHttp，对应 OkHttpRibbonConfiguration 配置类
#  restclient:
#    enabled: true # 设置使用 Jersey Client，对应 RestClientRibbonConfiguration 配置类
#  httpclient:
#    enabled: true # 设置使用 Apache HttpClient，对应 HttpClientRibbonConfiguration 配置类
