spring:
  application:
    name: scta-service-call-ribbon-consumer-custom-config-yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 28080

scta-service-call-ribbon-consumer-custom-config-yml:
  ribbon:
    # 负载规则全类名
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule