spring:
  application:
    name: scta-register-center-eureka-server

server:
  port: 18080

eureka:
  client:
    # 注册到 Eureka-Server，默认为 true
    register-with-eureka: true
    # 从 Eureka-Server 获取注册表，默认为 true
    fetch-registry: true
    service-url:
      # Eureka-Server 地址
      defaultZone: http://127.0.0.1:8761/eureka/
      # defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/  安全认证模式
