spring:
  application:
    name: scta-service-call-dubbo-quick-strat-provider
  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        # Nacos 服务器地址
        server-addr: 127.0.0.1:8848

# Dubbo 配置项，对应 DubboConfigurationProperties 类
dubbo:
  scan:
    # 指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.dumas.scta.service.call.dubbo.quick.start.provider.service.impl
  # Dubbo 服务暴露的协议配置，对应 ProtocolConfig Map
  protocols:
    dubbo:
      # 协议名称
      name: dubbo
      # 协议端口，-1 表示自增端口，从 20880 开始
      port: -1
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    # 指定 Dubbo 服务注册中心的地址
    address: spring-cloud://127.0.0.1:8848
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    # 设置订阅的应用列表，默认为 * 订阅所有应用
    subscribed-services: ''

management:
  endpoints:
    web:
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        include: '*'
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      # 是否开启。默认为 true 开启。
      enabled: true
      # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示
      show-details: ALWAYS