spring:
  application:
    name: scta-mq-stream-kafka-producer-partition
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binder 配置项，对应 BinderProperties Map
      # binders:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        # 目的地。这里使用 Kafka Topic
        demo01-output:
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
            # Producer 配置项，对应 ProducerProperties 类
          producer:
            # 分区 key 表达式。该表达式基于 Spring EL，从消息中获得分区 key。
            partition-key-expression: payload['id']
    # Spring Cloud Stream Kafka 配置项
      kafka:
        # Kafka Binder 配置项，对应 KafkaBinderConfigurationProperties 类
        binder:
          # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
          brokers: 127.0.0.1:9092
        # Kafka 自定义 Binding 配置项，对应 KafkaBindingProperties Map
        bindings:
          demo01-output:
            # Kafka Producer 配置项，对应 KafkaProducerProperties 类
            producer:
              # 是否同步发送消息，默认为 false 异步。
              sync: true

server:
  port: 18080