spring:
  application:
    name: scta-mq-stream-rocketmq-provider-orderly
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        demo01-output:
          # 目的地。这里使用 RocketMQ Topic
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
          # Producer 配置项，对应 ProducerProperties 类
          producer:
            # 分区 key 表达式。该表达式基于 Spring EL，从消息中获得分区 key
            partition-key-expression: payload['id']
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          # RocketMQ Namesrv 地址
          name-server: 127.0.0.1:9876
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          demo01-output:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              # 生产者分组
              group: test
              # 是否同步发送消息，默认为 false 异步。
              sync: true

server:
  port: 18080