server:
  port: 8082
spring:
  application:
    name: scta-mq-bus-rocketmq-listener
  # Bus 相关配置项，对应 BusProperties
  cloud:
    bus:
      # 是否开启，默认为 true
      enabled: true
      # 目标消息队列，默认为 springCloudBus
      destination: springCloudBus

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: 127.0.0.1:9876