server:
  port: 28080

spring:
  application:
    name: scta-service-call-feign-consumer-custom-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    com.dumas.scta.service.call.feign.consumer.custom.config: DEBUG

feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: BASIC
      # 客户端级别配置
      scta-service-call-feign-provider:
        logger-level: FULL