spring:
  application:
    name: scta-mq-bus-kafka-listener
  # Kafka 配置项，对应 KafkaProperties 配置类
  kafka:
    # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
    bootstrap-servers: 127.0.0.1:9092
  # Bus 相关配置项，对应 BusProperties
  cloud:
    bus:
      # 是否开启，默认为 true
      enabled: true
      # 目标消息队列，默认为 springCloudBus
      destination: springCloudBus