spring:
  application:
    name: scta-service-call-grpc-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  # gRPC 客户端配置，对应 GrpcChannelsProperties 配置类的映射
  client:
    scta-service-call-grpc-user-service:
      negotiation-type: plaintext